//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Drawing;
using System.Runtime.CompilerServices;

namespace Otel.Properties
{
    [CompilerGenerated, DebuggerNonUserCode, GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    internal class ResourcesBase
    {
        internal static Image kirmizi_yatak;

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yesil_yatak3
        {
            get
            {
                object obj = ResourceManager.GetObject("yesil_yatak3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}